# This file is auto-generated by setup.sh

TELEGRAM_BOT_TOKEN = "7033706465:AAFdnohcKiDUpXTEPebhbwEDSKU6G0w_0xE"
TELEGRAM_CHAT_ID = "6551838718"
BACKUP_DIRECTORIES = ["/root/mamad","/root/ali"]
BACKUP_EXPIRE_DAYS = 7
