#!/bin/bash

CONFIG_FILE="config.py"
CRON_COMMENT="# TeleBackuper Cron Job"
PYTHON_CMD="python3"
MAIN_SCRIPT="main.py"

# 🎨 رنگ‌ها
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

# 🧩 گرفتن ورودی از کاربر
prompt_input() {
    local prompt_text=$1
    local var
    read -rp "${YELLOW}${prompt_text}${NORMAL}: " var
    echo "$var"
}

# 📝 نوشتن فایل config.py
write_config() {
    echo -e "\n${CYAN}🔧 Generating config.py ...${NORMAL}"
    cat <<EOF > $CONFIG_FILE
# This file is auto-generated by setup.sh

TELEGRAM_BOT_TOKEN = "${BOT_TOKEN}"
TELEGRAM_CHAT_ID = "${CHAT_ID}"
BACKUP_DIRECTORIES = [$(echo $DIRS | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/')]
BACKUP_EXPIRE_DAYS = 7
EOF
    echo -e "${GREEN}✅ config.py created successfully.${NORMAL}"
}

# ⏱️ افزودن کرون جاب
setup_cron_job() {
    CRON_INTERVAL="*/$INTERVAL * * * *"
    CRON_CMD="$CRON_INTERVAL cd $(pwd) && $PYTHON_CMD $(pwd)/$MAIN_SCRIPT >> /tmp/telebackuper.log 2>&1"

    # حذف کرون قبلی با همین کامنت
    (crontab -l 2>/dev/null | grep -v "$CRON_COMMENT"; echo "$CRON_CMD $CRON_COMMENT") | crontab -
    echo -e "${GREEN}✅ Cron job added to run every $INTERVAL hour(s).${NORMAL}"
}

# 📋 نمایش منو
main_menu() {
    while true; do
        clear
        echo -e "${BOLD}${CYAN}"
        echo "╔═════════════════════════════════════════╗"
        echo "║         TeleBackuper Setup Tool         ║"
        echo "╠═════════════════════════════════════════╣"
        echo "║ 1) 🚀 Install / Configure                ║"
        echo "║ 2) 🛠️  Change Configuration (manual)     ║"
        echo "║ 3) ❌ Exit                               ║"
        echo "╚═════════════════════════════════════════╝"
        echo -e "${NORMAL}"

        read -rp "🔢 Enter your choice [1-3]: " choice

        case $choice in
            1)
                clear
                echo -e "${CYAN}🚀 Starting installation...${NORMAL}"
                BOT_TOKEN=$(prompt_input "🔑 Enter your Telegram Bot Token")
                CHAT_ID=$(prompt_input "🆔 Enter your numeric Chat ID")
                DIRS=$(prompt_input "📂 Enter directories to backup (comma-separated)")
                INTERVAL=$(prompt_input "⏱️  Enter interval in hours for cron job")

                write_config
                setup_cron_job

                echo -e "\n${GREEN}✅ Installation complete!${NORMAL}"
                read -rp "🔁 Press Enter to return to menu..."
                ;;
            2)
                echo -e "${YELLOW}🛠️  You can manually edit '${CONFIG_FILE}' file.${NORMAL}"
                sleep 2
                ;;
            3)
                echo -e "${CYAN}👋 Exiting setup. Goodbye!${NORMAL}"
                exit 0
                ;;
            *)
                echo -e "${RED}❌ Invalid choice. Please select 1, 2, or 3.${NORMAL}"
                sleep 1.5
                ;;
        esac
    done
}

# 🎬 اجرای منو
main_menu
